### ISSUE TITLE
compability - test with other delphi or free pascal versions

### ISSUE THREAD

**Issue by Hugie** [Hugie/lz4-delphi#3]
Only XE3 is tested. This is not enough. Help needed.

**Comment by dummzeuch** [comment]
It compiles with Delphi 10.2, albeit with a ton of hints and warnings (one of them a bug see issue #9)
A simple test seems to work: Compressing a file and then decompressing it results in the same content. What kinds of tests do you want the "help" to perform?
I could compile and test with every version from Delphi 6 to Delphi 12, but without having tried it, I am quite sure it won't compile with anything less than XE. On the other hand - again without having tried it - I am sure it will compile fine with Delphi 10.3 and later.

**Comment by dummzeuch** [comment]
It also compiles with Delphi 11, as expected.
I discovered that there is a conditional define WriteOutResults in lz4d.text which outputs some statistics. To actually run the tests, one has to supply a file to run the tests on.
I have cloned the repository and fixed issue #9 and added projects for the test program for Delphi 10.2 and Delphi 11 (for now). I won't bother with pull requests, since this project seems to be dead
 @Hugie if you are still actively maintaining it, please contact me and I will create those pull requests.

**Comment by Hugie** [comment]
Hi @dummzeuch, i sent you a message on mastodon with further informations.
I am happy to accept pull request.

**Comment by dummzeuch** [comment]
Does not compile with Delphi 2007 and cannot easily be adapted to it because Delphi 2007 does not support the supplied object files.

**Comment by dummzeuch** [comment]
It seems that the library is compatible to all Delphi versions from XE2 on. The linker does not like the object file format for older Delphi versions (tested: 2007 and XE, but I am sure the result would be the same for anything in between and older than 2007). The code would compile for those too, if the unit name prefixes are removed.

**Comment by Hugie** [comment]
Thank you very much for all your work. I am closing this ticket since we now know the Delphi Version limitations.
